recent search tabs feature enhancement
OlivierJM/powercut pull request #18
Opened 2024-03-20 14:43 UTC by josh-susinth

Save recently searched place [#10](https://github.com/OlivierJM/powercut/pull/url)

- will save three recent searches
- enabled cookies to persist the recent searches for 7 days
- Display them under the search field
- Display them in horizontal stack
- Each of these items should be clickable and once clicked it should trigger the find schedule function.
- They should only show before the user has searched.
- [work sample](https://drive.google.com/file/d/1ozK9G4FXnEljzmrdmwqQPUtLMnkmwsxB/view?usp=sharing)

2024-03-20 14:46 UTC, josh-susinth commented
Hi @OlivierJM , I created another PR. Previous PR is now closed as I messed up with yarn.lock.

2024-03-20 15:58 UTC, josh-susinth commented
> > Hi @OlivierJM , I created another PR. Previous PR is now closed as I messed up with yarn.lock.
> 
> Thanks @josh-susinth I just had not enough time to review it but I will take a look at this in the coming hours. Thanks a lot for this great work.

sure @OlivierJM looking forward to it. Also to note, this is my first OS contribution so pretty novice with the development environment and checks :)

2024-03-20 16:07 UTC, josh-susinth commented on src/components/RecentSearch/RecentSearch.tsx
> +const RecentSearchTab = ({ onTabSelect, onTabDelete, place }:
Sure, will do that

2024-03-20 16:07 UTC, josh-susinth commented on src/components/Schedule/Finder.tsx
> +  const onOptionSelect = async (place: string) => {
Ok. Will remove it

2024-03-20 16:07 UTC, josh-susinth commented on src/components/Schedule/Finder.tsx
> +          recentSearches && recentSearches.split('|').map((place) =>
Yeah sure

2024-03-20 16:09 UTC, josh-susinth commented
> > > > Hi @OlivierJM , I created another PR. Previous PR is now closed as I messed up with yarn.lock.
> > > 
> > > 
> > > Thanks @josh-susinth I just had not enough time to review it but I will take a look at this in the coming hours. Thanks a lot for this great work.
> > 
> > sure @OlivierJM looking forward to it. Also to note, this is my first OS contribution so pretty novice with the development environment and checks :)
> 
> You did great, just minor things I added comments above and thanks a lot 🚀 🙌🏽

Thank you and will make the changes soon

2024-03-20 16:55 UTC, josh-susinth commented on src/components/RecentSearch/RecentSearch.tsx
> +        <Button
Yeah , differentiating the button from main will be good. But centering the horizontal would make the buttons go to next row if the city name is of medium to large length. Currently , it only happens for large length city names. What do you think?

2024-03-20 22:16 UTC, Mwimwii requested changes

2024-03-20 22:16 UTC, Mwimwii commented on src/hooks/useCookie.ts
> +function getCookieObject(key: string): string {
change to just `getCookie` since you're returning a string

2024-03-20 22:16 UTC, Mwimwii commented on src/hooks/useCookie.ts
> +                cookieString = `${cookieString}; expires=${date}`;
I think you may require to use `date.toUTCString()` to store GMT time for the expiry

2024-03-23 17:20 UTC, OlivierJM commented
@josh-susinth let us know if you need any help

2024-03-24 11:30 UTC, josh-susinth commented on src/hooks/useCookie.ts
> +                cookieString = `${cookieString}; expires=${date}`;
![image](https://github.com/OlivierJM/powercut/assets/48217196/9861f60f-2539-4b51-82ff-ac0e516a7f2e)

its already storing UTC time only

2024-03-24 12:46 UTC, josh-susinth commented on src/components/RecentSearch/RecentSearch.tsx
> +        <Button
![image](https://github.com/OlivierJM/powercut/assets/48217196/b48c682c-76fb-4bb9-b4bd-a28cd54da3cb)
![image](https://github.com/OlivierJM/powercut/assets/48217196/5d3a59be-3e4c-49c9-a4d5-f6777987a2db)

is this okay?

2024-03-24 12:52 UTC, OlivierJM commented on src/components/RecentSearch/RecentSearch.tsx
> +        <Button
This looks okay to me @Mwimwii what do you think ?

2024-03-24 15:15 UTC, Mwimwii commented on src/components/RecentSearch/RecentSearch.tsx
> +        <Button
Dude, talk about perfection! @josh-susinth 👏👏👏👏

2024-03-24 17:14 UTC, josh-susinth commented
> @josh-susinth let us know if you need any help

hey @OlivierJM & @Mwimwii . development is completed and resolved both of your comments too.  Since I'm new to writing unit tests, it would take some time for me to finish writing test cases for this. Though I've written a very basic test case, looks like writing test cases for this feature is a bit more tedious than I expected. I will try to push them ASAP.

2024-03-28 07:15 UTC, OlivierJM commented
> > @josh-susinth let us know if you need any help
> 
> hey @OlivierJM & @Mwimwii . development is completed and resolved both of your comments too. Since I'm new to writing unit tests, it would take some time for me to finish writing test cases for this. Though I've written a very basic test case, looks like writing test cases for this feature is a bit more tedious than I expected. I will try to push them ASAP.
> 
> would be helpful if anyone of you can help me with this


@josh-susinth I have added more tests but it is on this branch https://github.com/OlivierJM/powercut/tree/recentFeature can you please sync that branch with yours and push back to this PR then we can merge it. 🙏🏽

2024-03-28 09:52 UTC, OlivierJM commented
Or you can merge this https://github.com/josh-susinth/powercut/pull/1/files into your branch and it will reflect here.

2024-03-29 18:22 UTC, josh-susinth commented
> Or you can merge this https://github.com/josh-susinth/powercut/pull/1/files into your branch and it will reflect here.

@OlivierJM merged your changes

2024-03-30 17:17 UTC, OlivierJM approved these changes

2024-03-30 17:22 UTC, merged